### ISSUE TITLE
MBTiles Metadata (Center) incorrect

### ISSUE THREAD

**Issue by muesliq** [osm2vectortiles/osm2vectortiles#113]
When uploading an MBTiles file from http://osm2vectortiles.org/ to Mapbox Studio, I get "Center lon value must be between bounds [east/west lon value corresponding to that region]". 

Could be a Mapbox Studio error but my guess is, it's a problem in the files. (Sorry, if not!)

Tried Switzerland, Croatia, Portugal and Zurich.

![screen shot 2016-01-12 at 15 22 24](https://cloud.githubusercontent.com/assets/1606618/12267019/68ff60e6-b946-11e5-9497-b737e8ebb9e0.png)

![screen shot 2016-01-12 at 15 14 50](https://cloud.githubusercontent.com/assets/1606618/12267018/68febae2-b946-11e5-8382-2962134dd851.png)

**Comment by lukasmartinelli** [comment]
Thanks. Hmm the bounds are indeed wrong. I guess all bounds on all extracts
are corrupt :(

If I update the bounds of the MBTiles to the max. bounds with `sqlite3` it works and I can upload it.

```bash
sqlite3 zurich.mbtiles
```

```sql
update metadata
set value='-180,-85.0511,180,85.0511'
where name='bounds'
```

Need to set new bounds for each extract. I previously used the bounds of the bounding box but perhaps in the wrong order. In worst case I just update the bounds to the max. value.

**Comment by lukasmartinelli** [comment]
> Could be a Mapbox Studio error but my guess is, it's a problem in the files. (Sorry, if not!)

Sadly you can't upload the file even then because some rogue tiles (a few dozen) exceed the 500K limit.
If you want to design a map in the new Mapbox Studio I suggest you use their normal Mapbox Streets v5 or v6 and then switch to osm2vectortiles in production.
We are pretty close to their data set except for terrain data.

This is a custom styled map I am working on that entirely works with osm2vectortiles.
http://schweizerkarte.lukasmartinelli.ch/#8/47.380/8.520
https://github.com/lukasmartinelli/schweizerkarte
But for designing it I work in Mapbox Studio and just export the `json` file when I am finished.

We hope we can soon get all tiles below the 500K limit in the next rendering of the world.

**Comment by muesliq** [comment]
Thanks @lukasmartinelli for checking!

**Comment by numenor** [comment]
I have made the experience (for Andorra, Monaco, Vatican City), that the bounds actually seem correct, but as reported by the Mapbox Studio importer, the center coordinates are wrong. If I modify the mbtiles sqlite "metadata" table, row "center" with the averaged min/max lon and min/max lat coordinates taken from the "bounds" row (and select an appropriately high center zoom level, and remove lower zoom level tile mappings from the mappings table, to circumvent the 500KB limit by accepting missing low zoom level tiles), then I have success with the upload (tested for Monaco).

**Comment by lukasmartinelli** [comment]
> If I modify the mbtiles sqlite "metadata" table, row "center" with the averaged min/max lon and min/max lat coordinates taken from the "bounds" row

Thanks @numenor. I use this approach now to calculate the center of each MBTile https://github.com/osm2vectortiles/osm2vectortiles/commit/b0f3679a6261e05164ae61f66e6a1eb3a2100e4c.
