### ISSUE TITLE
Test dirty tile detection for entire planet

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#148]
- Import of entire planet
- Import Diff Updates for entire planet

**Comment by lukasmartinelli** [comment]
Okay good and bad news.

Using the planet PBF  from  *2016-02-29* and doing diff updates until *2016-03-09* covers **10 days of updates.** Applying the diff updates with imposm3 takes around 3 hours.

Detecting the dirty tiles of the 10 days only takes  **1 hour** which I am very happy with - hurray.

Now the bad part: 10 days of changes already affects **42'802'075** tiles. Much more than we expected. This really might require distributed processing of the updates due to the huge amount of tiles.
But we also need to double check whether we do some serious mistakes and the tile count is therefore so high.

So 10 days ~= 43 million tiles. If we want to continuously rerender the world updates on a single machine (to keep it cheap) this means we must be finished with rendering the vector tiles in at least 10 days to be ready for the next update coming in. That could actually still be doable on a single fast server (thinking of reinstating the fat HSR server again).

**Comment by lukasmartinelli** [comment]
Good news.

Adding the objects from #210 only adds a 3 million tiles on top for the same time span.
**45263435** tiles for 10 days. This hints at the correctness of the hypothesis that **a few tiles change very often**. Takes ~  **1hour 50 minutes** for the entire world (including solving #210 #183), which is not bad but not perfect as well. We can still do a lot of optimisation to avoid querying `osm_delete` tables on the wrong zoom levels if we want to bring that time frame down.
