### ISSUE TITLE
Merge changes from diff into pbf

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#151]

**Comment by lukasmartinelli** [comment]
To elaborate the problem.
When you run `import-diff` it will look at the timestamp of PBF and then fetch all changes since then and apply them.
Now the problem is if you run this one day later it will do the same again but this time download the diffs for two days which means too many rows get updates than there should be.
One way to solve it is to always apply the downloaded diffs to the planet PBF in the `import` folders. This then ensures that **the PBF file in import always matches the data that is in the database**. Which is a nice guarantee to have.
