### ISSUE TITLE
[Question] Why are raster and vector maps so different?

### ISSUE THREAD

**Issue by muesliq** [osm2vectortiles/osm2vectortiles#158]
I noticed on the examples page that raster and vector maps are very different in how they show data and which data they show, despite using the same stylesheet (OSM bright). How come?
![screen shot 2016-03-04 at 17 07 46](https://cloud.githubusercontent.com/assets/1606618/13532798/b5fbc1cc-e22d-11e5-9e4b-89abe3d6cc37.png)

**Comment by lukasmartinelli** [comment]
> I noticed on the examples page that raster and vector maps are very different in how they show data and which data they show, despite using the same stylesheet (OSM bright). How come?

Good question.
The OSM Bright style for Mapbox GL and Mapnik are different. There is much room to optimize in Mapbox GL OSM Bright style (weird that they haven't done it - even on Mapbox.com the raster OSM Bright looks better). But that is out of our control, we did not touch the styles and let them be maintained by Mapbox and other people.

- https://github.com/mapbox/mapbox-gl-styles
- https://github.com/mapbox/mapbox-studio-osm-bright.tm2


In the future we want to go more in the direction of making sure Mapbox GL looks good instead of traditional raster maps (with Mapbox Streets v7 it is probably not possible to make the data work well with GL styles (which depend on v7) and raster maps (which depend on Mapbox Streets v5).

**Comment by muesliq** [comment]
Thanks! Differences in the style sheets explain everything. (They shouldn't use the same name for both..)
