### ISSUE TITLE
Update mbtiles based on new OSM Planet diffs

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#16]
- Update mbtiles whenever new OSM Planet data is available

**Comment by lukasmartinelli** [comment]
Imposm supports the diff mode and importing changes files works however now that we see how much time rendering the vector tiles MBTiles of the whole world takes we need to think about our approach.

We cannot simply rerender the tiles, instead we would have to keep track of the changed tiles and explicitly rerender those tiles. This is quite a big feature if we would really want to do that.

Perhaps this requirement of updating the world MBTiles does no longer fit into the time budget of this project.

**Comment by klokan** [comment]
+1

Lower priority, FINAL milestone. If time allows...

BTW Do we know how exactly Wikimedia's kartoherian detects the dirty tiles?

**Comment by klokan** [comment]
WikiMedia uses osm2pgsql expiry list method:
See: https://wiki.openstreetmap.org/wiki/Tile_expire_methods

The OmniScale has some private scripts for detecting dirty tiles (which they use together with imposm3).

Some people use: Matt's ruby scripts: http://svn.openstreetmap.org/applications/utils/export/tile_expiry/
It would make sense to somehow reuse the information from the mapnik data tiles for the expiry.

**Comment by lukasmartinelli** [comment]
I don't know where to best put this but a few things I noticed when we talked with people about the project

- People care about labels and label ranks -> new idea there was using Wikipedia links of OSM data to determine importance (but that's a topic for itself)
- People don't like that data in the vector tiles might be missing because it is not considered important by us
- People do like that there is an open alternative to the all mighty Mapbox
- It was asked pretty quickly, how the MBTiles would get updated
- Disputed borders really are kind of a undecided problem. People map the border and set `disputed=yes`. And borders are the relations that are updated the most.
- People are also interested in rendering MBTiles themselves (so making our PostGIS / export stack approachable would make also sense - it is not just for us)
- Documentation will be absolutely crucial - explaining the project on the site and helping as fast as possible to get to the goal of MBTiles is important
- Packaging tessera/Mapbox GL locally makes for an extrem good demo use case even though it is perhaps of limited use. One can just give the people an executable (on a branded stick?), they click on it and choose an MBTiles and voilà - a nice map rendered from **own** data from OpenStreetMap. This will get people talking. Docker while very powerful and actually the end goal is an additional obstacle when just trying to get started as fast as quickly (My guess is especially for Windows people)

**Comment by klokan** [comment]
Reopening - and removing from FINAL milestone.

**Comment by lukasmartinelli** [comment]
yes..detaching from milestone makes more sense than closing it.

**Comment by lukasmartinelli** [comment]
Next step is to apply the diff updates with imposm3 to figure out how diff updates work.

Read the Golang https://github.com/omniscale/imposm3 code to find out what extra information about changed tiles (from applying the diffs) is available and how we can use that to detect dirty tiles.

**Comment by lukasmartinelli** [comment]
Goal: On the osm2vectortiles downloads we want to have daily diffs of the data.

For each update that imposm3 does on the database we need to know a timestamp. Perhaps we can implement a `INSERT`  trigger that will set a new timestamp or work with row versioning directly or perhaps implement something in imposm3 to track changes directly in the database.

Once we have a timestamp information about each row we can filter for the newest changed shapes and only rerender those tiles.

**Comment by lukasmartinelli** [comment]
Geofabrik provides minutely diffs for countries. http://download.geofabrik.de/europe.html

**Comment by ImreSamu** [comment]
Hi! 
some side notes based on my research in this topic:

* I agree:  The quick way now to detect changes 
 * the postgresql side with: `insert` , `delete` trigger  ( As I know not need `update` trigger,  - but please verify ! )  and save  the `old` and the `new`   -  `geom` 
 * the `delete` trigger is also important!  ( you only metioned the  a `INSERT` trigger )
 
* I have created some experimental imposm3 mapping types - like :  [ `jobstart_datetimeutc` timestamp]
(https://github.com/ImreSamu/imposm3_fieldtypes/blob/master/mapping/fieldtype_jobstart_datetimeutc.go) , maybe you can use!
important: this code not working with the current imposm3 version,  need adapting.  If you need help : ping me - and I will create a patch.

* There is an interesting project : https://github.com/mapbox/tile-cover
 * maybe some ideas can be reused,
 * or temporary used in the toolchain
 * or implement the algorithm in the imposm3 side ( golang )

**Comment by lukasmartinelli** [comment]
> I have created some experimental imposm3 mapping types - like : jobstart_datetimeutc timestamp , maybe you can use!
> important: this code not working with the current imposm3 version, need adapting. If you need help : ping me - and I will create a patch.

Thanks a lot for participating in the discussion!!
We will check that out. Sounds like what we need!

**Comment by lukasmartinelli** [comment]
> There is an interesting project : https://github.com/mapbox/tile-cover

Thanks for the golden tip! **tile-cover** is exactly what we need.

**Comment by manuelroth** [comment]
This issues is not needed anymore as it is now implemented and the progress is documented many other issues.
