### ISSUE TITLE
Create summary views

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#172]
- Think about good naming for summary views

**Comment by lukasmartinelli** [comment]
Create views that query all zoom levels that can be used in the detect dirty tile process.

Example.

```sql
CREATE VIEW landuse_zoom_level_changes_geom AS (
	SELECT osm_id, timestamp, geometry FROM landuse_z13toz14
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z12
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z11
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z10
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z9
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z8
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z7
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z6
	UNION
	SELECT osm_id, timestamp, geometry FROM landuse_z5
);
```

**Comment by manuelroth** [comment]
Naming of summary views: layer_{layer name}
Example: layer_admin, layer_landuse
Explanation: The view returns all geometries which are shown an every zoom level combined.

**Comment by klokan** [comment]
The dirty tiles detection is always very relevant to a zoom level - what is the purpose of this summary view exactly?

**Comment by lukasmartinelli** [comment]
> The dirty tiles detection is always very relevant to a zoom level - what is the purpose of this summary view exactly?

To create a list of osm_ids with their dirty tiles based on what changed
you cannot work with the table `osm_landusages` or `osm_roads` directly. 

Because the `osm_landusages` table actually is the source for both layers `landusage` and `landusage_overlay` and `osm_roads` for `bridge`, `tunnel`, `road`.
And the geometries of the tables can also be changed into different ones. Like POI point labels that were originally a polygon.

With the summary view we can get the list of changed geometries for a given layer
which then allows to query the OSM ids with their respective dirty tiles.
The summary view also removes the OSM ids that appear on many zoom levels (`UNION`).

We can then query all dirty tiles for a layer. The query below for the complex landusages layer actually completes in 40s which is pretty fast IMHO.
We still need to validate whether the query **really** returns the dirty tiles #149 
```sql
--Query all changed geometries for layer poi_label
WITH changed_geometries AS (
    SELECT osm_id, geometry FROM poi_label_zoom_level_changes
    WHERE timestamp = '2016-03-09 14:15:02'
--Calculate the dirty tiles for each OSM id
), changed_tiles AS (
    SELECT DISTINCT c.osm_id, t.tile_x AS x, t.tile_y AS y, t.tile_z AS z
    FROM changed_geometries AS c
    INNER JOIN LATERAL overlapping_tiles(c.geometry) AS t ON true
)
SELECT c.x, c.y, c.z FROM landuse_z13toz14 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z BETWEEN 13 AND 14
UNION

SELECT c.x, c.y, c.z FROM landuse_z12 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 12
UNION

SELECT c.x, c.y, c.z FROM landuse_z11 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 11
UNION

SELECT c.x, c.y, c.z FROM landuse_z10 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 10
UNION

SELECT c.x, c.y, c.z FROM landuse_z9 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 9
UNION

SELECT c.x, c.y, c.z FROM landuse_z8 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 8
UNION

SELECT c.x, c.y, c.z FROM landuse_z7 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 7
UNION

SELECT c.x, c.y, c.z FROM landuse_z6 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 6
UNION
SELECT c.x, c.y, c.z FROM landuse_z5 AS l
INNER JOIN changed_tiles AS c ON c.osm_id = l.osm_id AND c.z = 5
````
