### ISSUE TITLE
Extracts: Correct Metadata fields

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles#247]
- Currently only the fields attribution, version, minzoom, maxzoom, name, description, bounds and center [get updated](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/tools/create-extracts/create-extracts.sh#L118) during the extract creation
- [ ] Update additional fields basename, id, filesize
- [ ] Correct attribution field to appear as link
- [ ] Update name to osm2vectotiles
- [ ] Update metadata of city and country extracts on switch s3

### Metadata of liechtenstein extract
![bildschirmfoto 2016-04-13 um 10 43 32](https://cloud.githubusercontent.com/assets/1810384/14487857/488ead46-0165-11e6-8714-77622d3313a2.png)

**Comment by lukasmartinelli** [comment]
Actually most of this stuff is not even required. https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md

So I suggest we remove the metadata fields:
- `filesize` (If you have the MBTiles you know the size)
- `id` ?? (don't know which id of what is meant)

We also set the version in the name in the future as done in #215 and since the `version` field is not official we can remove it as well.
The `basename` field is probably the basename of the vector tile file.

**Comment by sfkeller** [comment]
@lukasmartinelli you are right regarding keys id and filesize. 
But according to the spec. these five keys are required: name, type, version, description and format. Especially version is something a reader should check. 
Then these are keys are suggested by the spec. (and I would suggest it too): bounds and attribution.

**Comment by lukasmartinelli** [comment]
Pushing the extracts now, this just takes very very long but after that all metadata will be up to date (except a few things that are always derived from the planet source like attribution - this will only change once we release the new planet file).
