### ISSUE TITLE
imposm3 mapping update research.   conclusion ->  use_single_id_space: true 

### ISSUE THREAD

**Issue by ImreSamu** [osm2vectortiles/osm2vectortiles#281]
I made some test with imposm3 diff update and with the current [osm2vectortiles mapping.yml] (https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-osm/mapping.yml )
My suggestion:   **use_single_id_space: true **

The problem :   this is dangerous combination:
* `type_mappings` + multiple osm type
* with `imposm3 diff`
* with `use_single_id_space: false`

My test method :
* theoretical input data - see full test code [y.sh](https://gist.github.com/ImreSamu/9cbad28eb0a211105934b3718a25fda6#file-y-sh)
* 3 nodes, 3 ways ,3 relations -> testing   osm_id collision  with mapping.yml
* modified only one object  -  key: `name`+ `-UPDATED!!!!!`
 * and checked the update mechanism.
  * with  `use_single_id_space: false`
  * with  `use_single_id_space: true`

Result:
* without : use_single_id_space: true  -> some data loss.

Why:
*   nodes and ways  can be a same  `osm_id`  and when one of is updated, both of them is deleted, but only the updated inserted again.
 *   select  osm_id=2  
   *  2 | hamlet | n2-place-hamlet ( osm_id =2 and NODE )
    * 2 | islet      | w2-place-islet-inner ( osm_id=2 and  WAY )

see more: 
* http://gis.stackexchange.com/questions/103572/are-osm-ids-unique-over-all-object-types/103585

### use_single_id_space: false  -  current  settings
https://gist.github.com/ImreSamu/9cbad28eb0a211105934b3718a25fda6#file-single_id_false_test_report-md
in the worst case  -  data lost - see    r3-place-archipelago 

```sql
 osm_id |       type        | place_geometry_name____before_diff_mod_r3 
--------+-------------------+-------------------------------------------
     -3 | archipelago       | r3-place-archipelago
     -2 | island            | r2-place-island
     -1 | residential       | r1-landuse-residential
      1 | neighbourhood     | n1-place-neighbourhood
      2 | hamlet            | n2-place-hamlet
      2 | islet             | w2-place-islet-inner
      3 | isolated_dwelling | n3-place-isolated_dwelling
      3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
(8 rows)

 osm_id |       type       | place_geometry_name____after_diff_mod_r3 
--------+------------------+------------------------------------------
     -3 | archipelago      | r3-place-archipelago-UPDATED!!!!!
     -2 | island           | r2-place-island
     -1 | residential      | r1-landuse-residential
      2 | islet            | w2-place-islet-inner
      2 | hamlet           | n2-place-hamlet
      3 | aboriginal_lands | w3-boundary-aboriginal_lands-inner
(6 rows)
```
expecting : same record as before  , now  only 6  ( instead of 8 )
missing:
* n1-place-neighbourhood
* n3-place-isolated_dwelling
 

### use_single_id_space: true
https://gist.github.com/ImreSamu/9cbad28eb0a211105934b3718a25fda6#file-single_id_true_test_report-md

this is so much better!
`r3-place-archipelago-UPDATED!!!!!` - ok   and no other osm_id -s destroyed.

```sql
       osm_id        |       type        | place_geometry_name____before_diff_mod_r3 
---------------------+-------------------+-------------------------------------------
 -100000000000000003 | archipelago       | r3-place-archipelago
 -100000000000000002 | island            | r2-place-island
 -100000000000000001 | residential       | r1-landuse-residential
                  -3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
                  -2 | islet             | w2-place-islet-inner
                   1 | neighbourhood     | n1-place-neighbourhood
                   2 | hamlet            | n2-place-hamlet
                   3 | isolated_dwelling | n3-place-isolated_dwelling
(8 rows)

       osm_id        |       type        | place_geometry_name____after_diff_mod_r3 
---------------------+-------------------+------------------------------------------
 -100000000000000003 | archipelago       | r3-place-archipelago-UPDATED!!!!!
 -100000000000000002 | island            | r2-place-island
 -100000000000000001 | residential       | r1-landuse-residential
                  -3 | aboriginal_lands  | w3-boundary-aboriginal_lands-inner
                  -2 | islet             | w2-place-islet-inner
                   1 | neighbourhood     | n1-place-neighbourhood
                   2 | hamlet            | n2-place-hamlet
                   3 | isolated_dwelling | n3-place-isolated_dwelling
(8 rows)
```

_if you need my test code: ask - and I create a pull request._

**Comment by lukasmartinelli** [comment]
Such a great report @ImreSamu!

![You are the best](http://45.media.tumblr.com/2468d25581d5d747bb536ada3f5870ba/tumblr_nlat5ccdCs1tq4of6o1_500.gif)

> for NO osm_id collision ( or not use type_mappings )

We use the `type_mappings` primarily for OSM roads because otherwise we had for example for plazas linestrings and polygons twice. When we put them into the same table with type_mappings the first geometry type in the type_mappings matches first which is the behavior we want.

For `osm_place` it actually not really necessary.

> My suggestion: *use_single_id_space: true *

If we use the single id space and still want to use the Mapbox OSM ID format in the vector tiles
**we could "reproroject" the imposm3 OSM IDs back into normal OSM ID format and then apply the Mapbox format?**

*Or what about using the imposm3 id as ID for the vector tiles? There will be compression drawbacks?*


This would be kind of the most comfortable option (even though we have to throw away some code) because sometimes then we don't have to worry whether the geometry is polygon, point or linestring when we output the OSM ID (which would help because we now start having tables with points that originated from polygons).

**Comment by klokan** [comment]
So if I understand it correctly - the `use_single_id_space` is an internal imposm3 implementation of the what Mapbox OSM ID does - just done differently.

According to my understanding, both are convertable there and back and equal in semantic.

Imposm3 process the diffs correctly only if used with `use_single_id_space`.

Correct?

**Comment by lukasmartinelli** [comment]
Stating the things below mostly for myself for future reference.

> So if I understand it correctly - the use_single_id_space is an internal imposm3 implementation of the what Mapbox OSM ID does - just done differently.

Everyone needs to solve the problem that each OSM object type has a separate ID space (bad decision imho):
- Relation
- Way
- Node

And then again imposm builds real PostGIS geometries out of this. And so in the end you have the following combinations that still need a unique ID.

- Polygon
- Way
- Node
- Polygon (from Relation)
- Way (from Relation)

Imposm3 solves this by subtracting a huge number for all relations while Mapbox solves this with their `(id * 10) + {0..5}`. 

> According to my understanding, both are convertable there and back and equal in semantic.

**Given you now the geometry type of an object.**

> Imposm3 process the diffs correctly only if used with use_single_id_space.

Yes because we are using `type_mappings` for places and roads where we have both linestrings/polygons and points/polygons. If we would only use the normal `mapping` this wouldn't occur as different geometry types are then never in the same table.

**For the use case of highlighting a object on a vector tile map**.

Let's say we want to highlight a distinct building polygon (from address) we know a building polygon can either be:
- Polygon
- Polygon (from Relation)

So we need to query the Mapbox API for features with the osm id  `(osm_id * 10) + 2` and `(osm_id * 1) + 4`

**Comment by ImreSamu** [comment]
imho:

>So if I understand it correctly - the use_single_id_space is an internal imposm3 implementation 
>of the what Mapbox OSM ID does - just done differently.

from a bird's–eye view:   yes

>According to my understanding, both are convertable there and back and equal in semantic.

as I know the MapboxV7id containing more information  
* [ this `is_polygon` or NOT ? ]
see my proposed function
https://github.com/osm2vectortiles/osm2vectortiles/pull/287#issuecomment-214432750
 
 
>Imposm3 process the diffs correctly only if used with use_single_id_space.

my current understanding:
* with `type_mappings`    - this is a MUST have parameter.
* without `type_mappings` - this is useful ( but diff will work without use_single_id_space )

From QA view : `use_single_id_space:true`  is ideal for clean database design

( in the future )   I will re-check again, and I will try to create a patch for imposm3 - for warning other users! 


Summary:
* The 'no brainer' - safest settings for every case:  `use_single_id_space:true`

**Comment by ImreSamu** [comment]
>Or what about using the imposm3 id as ID for the vector tiles? 
>There will be compression drawbacks?

The `compression drawbacks` is my **speculation** - not fact or test based.

On the other hand - I will be interested the real size numbers ..
