### ISSUE TITLE
Data density too low

### ISSUE THREAD

**Issue by muesliq** [osm2vectortiles/osm2vectortiles#295]
I understand that data density and tile sizes are conflicting issues but I think that the data/feature density in osm2vectortiles is still too low. ZL = zoom level.

Some Examples:

## ZL 5 osm2vectortiles vs ZL 6 Google 

![z5](https://cloud.githubusercontent.com/assets/1606618/14821988/22d50fc4-0bcd-11e6-923f-46fa1f27bfc7.png)

Missing in oms2vectortiles: 

- [x] ZL5 Landuses (Forests) 
- [x] ZL5 Roads
- [x] ZL5 Cities/Places

(In return the regional borders could be pushed down one ZL IMHO.)

## ZL 6 osm2vectortiles vs ZL 6 Mapbox Street v7 

![z6](https://cloud.githubusercontent.com/assets/1606618/14822933/d12e5802-0bd0-11e6-8896-ad72ea9c8ac3.png)

- [x] ZL6 Cities/Places

## ZL 7 osm2vectortiles vs ZL 7 Mapbox Street v7 

![z7](https://cloud.githubusercontent.com/assets/1606618/14823085/7fc0db24-0bd1-11e6-8cca-1b4eb3946459.png)

- [ ] ZL7 Cities/Places

## ZL 8 osm2vectortiles

Data density ok I guess.

## ZL 9 osm2vectortiles vs ZL 9 Mapbox Street v7 

![z9](https://cloud.githubusercontent.com/assets/1606618/14823272/31c63f08-0bd2-11e6-88c1-9ea09b30bbc8.png)

- [ ] ZL9 Cities/Places
- [ ] ZL9 Landuse residential

## ZL 10 osm2vectortiles vs ZL 10 Mapbox Street v7 

![z10](https://cloud.githubusercontent.com/assets/1606618/14823410/c21bf8a4-0bd2-11e6-9b57-651cd6ae6758.png)

- [x] ZL10 Cities/Places
- [x] ZL10 Roads

## ZL 11 osm2vectortiles vs ZL 12 Google Maps

![z11](https://cloud.githubusercontent.com/assets/1606618/14823807/1b1dbcb6-0bd4-11e6-971b-976a08bf734e.png)

- [x] ZL11 Trains
- [x] ZL11 Small rivers

## ZL 12 osm2vectortiles vs ZL 12 Mapbox Street v7 

![z12](https://cloud.githubusercontent.com/assets/1606618/14824059/e2bd3bc0-0bd4-11e6-9ce1-808567cfa29b.png)

- [x] ZL12 Minor roads
- [x] ZL12 Water bodies
- [ ] ZL12 Cities/Places

## ZL 14+ osm2vectortiles
- [x] ZL14 House numbers (for use in ZL17+)

(It even seems as if the stylings of ZLs in old raster maps and ZLs in osm2vectortiles would correspond, yet as vector tiles are 4x the size of raster tiles zoom levels do not correspond. What is ZL6 in the Mapbox GL world is ZL7 in the world of raster maps and with Google Maps.)

**Comment by lukasmartinelli** [comment]
Thanks for the really detailed comparison.

> I understand that data density and tile sizes are conflicting issues but I think that the data/feature density in osm2vectortiles is still too low. ZL = zoom level.

How did you do the screenshots? Are you comparing the http://dev.vectortiles.osm2vectortiles.org.

**Comment by lukasmartinelli** [comment]
The good thing is that down to z8 or z9 we can easily rerender everything if we want to improve something since it is not that many tiles.

> ZL 5 osm2vectortiles vs ZL 6 Google

Cannot see immediate differences on z5.
http://dev.vectortiles.osm2vectortiles.org/#5.12/46.119/8.030

![screenshot from 2016-04-26 21-09-00](https://cloud.githubusercontent.com/assets/1288339/14830872/47c3fbe4-0bf3-11e6-9770-38ea3153a38e.png)

> ZL 6 osm2vectortiles vs ZL 6 Mapbox Street v7

The problem here is that we tested too much with Switzerland where the scalerank is mostly set for the important places. We can add more place labels but then mostly the client is responsible for filtering them by localrank.

What I do now in https://github.com/osm2vectortiles/osm2vectortiles/commit/807c7a986da46b1b51bc201dac32a6921d25b673 to improve density on z6 and z7 is to allow all `town` and `city` (even if no scalerank)
but I then limit the data to `localrank < 40`.

![screenshot from 2016-04-26 21-11-53](https://cloud.githubusercontent.com/assets/1288339/14830942/90a441b6-0bf3-11e6-96ba-cfe3703b8042.png)

> ZL 7 osm2vectortiles vs ZL 7 Mapbox Street v7

![screenshot from 2016-04-26 21-31-17](https://cloud.githubusercontent.com/assets/1288339/14831513/6962e06e-0bf6-11e6-976a-3e3c2200302e.png)


> ZL14 House numbers (for use in ZL17+)

We have the house numbers. The style is just not displaying them.

@manuelroth Want to talk a look at the other proposals?

**Comment by muesliq** [comment]
Great! I didn't know http://dev.vectortiles.osm2vectortiles.org/ - I had used our own styling plus http://osm2vectortiles.org/maps/ to check data density. 

Seems that you have solved most of the issues already. I have updated the list accordingly. Mainly in ZL7, 9 and 12 I still see problems.

**Comment by manuelroth** [comment]
### ZL 5 osm2vectortiles vs ZL 6 Google

Roads on z5 are fine now:
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14857760/ba0bb91c-0c9d-11e6-92e8-730843d51a8b.png)

### ZL 11 osm2vectortiles vs ZL 12 Google Maps

The rivers in Allmendingen are tagged as waterway=stream. Mapbox shows stream from zoom level 13 on. So we won't show them already from zoom level 11. However I found out that waterway=river are already shown from zoom level 7 on. Implemented this in the following pull request https://github.com/osm2vectortiles/osm2vectortiles/pull/298 . 

### ZL 12 osm2vectortiles vs ZL 12 Mapbox Street v7

Bigger water polygons are as of PR https://github.com/osm2vectortiles/osm2vectortiles/pull/299 show from zoom level 11 on. Minor roads are also visible.
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14857969/807ab3fa-0c9e-11e6-9999-91276e260aac.png)

**Comment by muesliq** [comment]
Great that you are caring about these details, guys! 

One thing mentioned in a checkbox but not illustrated yet: I think landuse=residential is important (even if Mapbox doesn't seem to agree). Two screenshots from http://Maptoolkit.net (our old raster rendering), look at the grey areas:

## ZL9 Raster (= ZL 8 Vector):

![z9](https://cloud.githubusercontent.com/assets/1606618/14881922/7c2caf0e-0d36-11e6-8b86-6791329e1b79.png)

## ZL11 Raster (= ZL10 Vector):

![z11](https://cloud.githubusercontent.com/assets/1606618/14881927/82629528-0d36-11e6-8516-38dcf541253b.png)

**Comment by lukasmartinelli** [comment]
There are two problems left here which is the city label density #308 and landuse residential #307 which will continue in separate issues since they are larger features.
The other things in this issue have already been resolved by @manuelroth (thanks!!).

BTW @muesliq nice article about Google Maps label placement http://www.justinobeirne.com/essay/what-happened-to-google-maps.

**Comment by pnorman** [comment]
> One thing mentioned in a checkbox but not illustrated yet: I think landuse=residential is important (even if Mapbox doesn't seem to agree).

at z8 what you generally want is built up place polygons, not landuse=residential
