### ISSUE TITLE
Water polygon edges are visible

### ISSUE THREAD

**Issue by hannesj** [osm2vectortiles/osm2vectortiles#300]
When adding an outline for the water polygons, in order to draw an slight edge on the shore, we get lines where the water polygons are cut of in the OSM water polygons.

![Example](http://api.digitransit.fi/map/v1/hsl-map/10/583/296@2x.png)

The style includes the following for style for water, which works with the Mapbox tiles, without creating these edges.

```
        {
            "id": "water",
            "type": "fill",
            "source": "vector",
            "source-layer": "water",
            "paint": {
                "fill-color": "#bee4f8",
                "fill-outline-color": "#a6d8f4"
            },
            "interactive": true,
            "layout": {}
        },
```

**Comment by lukasmartinelli** [comment]
> When adding an outline for the water polygons, in order to draw an slight edge on the shore, we get lines where the water polygons are cut of in the OSM water polygons.

Yes the data from http://openstreetmapdata.com/data/water-polygons is cut into different parts so that we don't have to handle the ocean as one gigantic polygon (no performance problems).

Which data are you using. What is currently released on osm2vectortiles.org?
It might be possible that because we use the osm_id as vector tile key in the next version that the water is handled in the vector tile as one huge polygon even if it is not
**But we don't have a fix for this.** We need to use the water from OpenStreetMapData.

I understand the need for having **nice coastline styles for ocean polygons**.
**Can you style the land instead of the water perhaps?**

**BTW** For what kind of project are you using osm2vectortiles in the map above? For http://dev.digitransit.fi/? We love to hear what people are using osm2vectortiles for and where we can help.

**Comment by hannesj** [comment]
> Which data are you using. What is currently released on osm2vectortiles.org?
It might be possible that because we use the osm_id as vector tile key in the next version that the water is handled in the vector tile as one huge polygon even if it is not
But we don't have a fix for this. We need to use the water from OpenStreetMapData.

We are currently using a self-generated tileset based on your Docker images just prior to merging #222.

> I understand the need for having nice coastline styles for ocean polygons.
Can you style the land instead of the water perhaps?

There is no land to be styled, as the land consists of just the background, which is colored using a solid color, making the water polygons our only choice to get nice colored coastlines. Somehow Mapbox has gotten this working, since using the same style with their vector tiles doesn't render edges between tiles and only on the coastlines. You might want to check what osm_ids they use for their water polygons.

> BTW Are you using osm2vectortiles for http://dev.digitransit.fi/ as you told us in #114? We love to hear what people are using osm2vectortiles for and where we can help. We hope that the next version will resolve most issues and it will bring along many many quality improvements.

Yes, we have been following your progress. We are currently using a self-generated tileset based on your Docker images just prior to merging #222. We have previously been using a different vector map style, which can be found [here](https://github.com/HSLdevcom/osm-bright.tm2source), but found your project to be much more complete.

In order to read more about our project, you can read more [here](http://www.digitransit.fi/en/)

**Comment by lukasmartinelli** [comment]
> There is no land to be styled, as the land consists of just the background, which is colored using a solid color, making the water polygons our only choice to get nice colored coastlines. Somehow Mapbox has gotten this working, since using the same style with their vector tiles doesn't render edges between tiles and only on the coastlines. You might want to check what osm_ids they use for their water polygons.

Yes we import the water not the land from OpenStreetMapData..

So the ideas that come to mind for fixing this problem:

- **Use a complete Water polygon**: Would result in performance problems since the vector tile renderer needs to request too much data for rendering a small part of the world.
- **Vector Tile Key**: How does Mapbox know what the polygon inside the vectortile is part of a bigger polygon? Perhaps since we use **0** as vector tile key then MapboxGL thinks that those are all part of the same polygon. **I will have a look into this**
- **Coastlines**: Use coastline data and then style the line with an outer shadow.  http://openstreetmapdata.com/data/coastlines

Since you are generating the osm2vectortiles vector tiles yourself (right?) you could import the coastlines [with shp2pgsql](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-external/import-water.sh) and then style the coast line.

I know that is not perfect but that would be one possible way how you can get this to look nice faster than waiting for us :)

> In order to read more about our project, you can read more here

Oh will love digging into this. Nice docs!
http://www.digitransit.fi/en/developers/service-catalogue/apis/map-api/

**Comment by lukasmartinelli** [comment]
Problem still exists (even though water has the same key).
You can see the fine styled lines on the right.

![screenshot from 2016-04-27 21-49-01](https://cloud.githubusercontent.com/assets/1288339/14866053/f3900930-0cc1-11e6-90c0-cc6250d6c485.png)

**Comment by hannesj** [comment]
Would a similar approach to the one specified in #297 work with this. Especially if extending the polygons outside the expected buffer.

**Comment by lukasmartinelli** [comment]
> Would a similar approach to the one specified in #297 work with this. Especially if extending the polygons outside the expected buffer.

You can collect the ocean polygons and combine them together into one polygon.
This could be done if you want to produce only a local extract but not for the world due to performance resons.

> Use a complete Water polygon: Would result in performance problems since the vector tile renderer needs to request too much data for rendering a small part of the world when rendering water.

If you run osm2vectortiles yourself I can do a branch with coastlines import and coastline layer and publish it there - but I don't want to add coastlines to the main project.

It is a bug that you cannot style the water polygons because they are split but it is also a high-invest low-return bug that we cannot fix in the main project without many hours (that we need to invest otherwise due to rendering schedule).
Sorry, hope that's ok for you.

**Comment by muesliq** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/769#issuecomment-197496089

**Comment by hannesj** [comment]
Thanks for your effort. I'll look what I can do locally for this. It's not a high priority bug for us either, I just wanted to document this somewhere.

If I don't find a nice solution we can just import the coastlines as linestrings, which can be styled separately.

**Comment by lukasmartinelli** [comment]
As discussed above there will be no general fix for this.

> If I don't find a nice solution we can just import the coastlines as linestrings, which can be styled separately.

If you plan on doing that just post on this issue again here and I will create a separate branch with an extended **import-external** container and a new layer. Setting up a new layer takes us not much time.

**Comment by ratrun** [comment]
Thank you for your great project! If took me quite a while to locate this.

As a consequence of the "wontfix" decision the style at 

https://github.com/osm2vectortiles/mapbox-gl-styles/blob/master/styles/bright-v9-cdn.json

should be better changed and the following part removed:

```
        {
            "id": "water_offset",
            "paint": {
                "fill-color": "white",
                "fill-opacity": 0.3,
                "fill-translate": [
                    0,
                    2.5
                ]
            },
            "metadata": {
                "mapbox:group": "1444849382550.77"
            },
            "interactive": true,
            "ref": "water"
        },
        {
            "id": "water_pattern",
            "paint": {
                "fill-translate": [
                    0,
                    2.5
                ],
                "fill-pattern": "wave"
            },
            "metadata": {
                "mapbox:group": "1444849382550.77"
            },
            "interactive": true,
            "ref": "water"
        }
```
This would prevent others from having the same problem with visible water tile edges.

**Comment by lukasmartinelli** [comment]
> Thank you for your great project! If took me quite a while to locate this.

Thanks @ratrun. You want to provide a PR for that since you are already know the change?

**Comment by lukasmartinelli** [comment]
Good work. You can see it in effect here: http://osm2vectortiles.org/maps/

**Comment by klokan** [comment]
For the water layer - union of polygons which are overlapping the bounding box of the tile which should be rendered - before sending it to Tilelive Mapnik for rendering PBF - could solve the problem. Not sure about the performance - ideally the union result should be cached by Postgres for nearby tiles and repeated use.
