### ISSUE TITLE
Map landuse=residential for low zoom level City Styling

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#307]
From #295 requested by @muesliq.
Landuse areas in the vector tiles allow cartographers to style cities on low zoom levels (where buildings do net yet appear). We don't know the size impact of such a decision but I can make a branch where the mapping is adapted to work this way.

## ZL8 Vector (= ZL 9 Raster):

![z9](https://cloud.githubusercontent.com/assets/1606618/14881922/7c2caf0e-0d36-11e6-8b86-6791329e1b79.png)

## ZL10 Vector (= ZL11 Raster):

![z11](https://cloud.githubusercontent.com/assets/1606618/14881927/82629528-0d36-11e6-8516-38dcf541253b.png)

**Comment by muesliq** [comment]
Great! I'd say the feature can be put in one large multipolygon, regardless of zoom level, to save space.

**Comment by manuelroth** [comment]
I will have a look into this, landuse=residential is already included in our [mapping](https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/import-osm/mapping.yml#L350), but it is currently only present on z14 in the vector tiles. Will create a style example.

**Comment by manuelroth** [comment]
The following style was used to style landuse=residential:
```json
{
            "id": "landuse_residential",
            "type": "fill",
            "metadata": {
                "mapbox:group": "1444849388993.3071"
            },
            "source": "mapbox",
            "source-layer": "landuse",
            "interactive": true,
            "filter": [
                "==",
                "class",
                "residential"
            ],
            "paint": {
                "fill-color": "#d3d3d3"
            }
        }
```
z8:
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14958229/033b0bac-108a-11e6-92cb-74bc679962c0.png)

z10:
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14958258/26206964-108a-11e6-9ed2-a14a8162a969.png)

@muesliq @numenor we have added landuse={residential, commercial, retail, military, railway} can you give a suggestion for each tag on which zoom levels do you think they are useful?

**Comment by muesliq** [comment]
Sure. 

- Residential, commercial, retail, railway: Z8
- Military: Z7

But I only know precise reasons for Residential, @numenor will be able to explain the other features (and if they are actually important).

**Comment by manuelroth** [comment]
Do you think it is necessary to have landuse=residential all the way down to z14 in the vector tiles?- Is it still useful on z14?

z14:
![compare_open_streets_with_mapbox_streets](https://cloud.githubusercontent.com/assets/1810384/14958813/c8417196-108c-11e6-9735-3329aa255422.png)

**Comment by muesliq** [comment]
Is it useful in high zoom levels? Yes. Is it absolutely necessary? I guess not.

![screen shot 2016-05-02 at 17 41 59](https://cloud.githubusercontent.com/assets/1606618/14958913/4a2414d4-108d-11e6-8215-f346e8a91315.png)

**Comment by numenor** [comment]
In our style, the following turned out to be sensible:
* residential: Z7 (=vector) all the way down to Z14 (in OSM landuse=residential is mapped to a high level of detail in several cities, blending well with parks, commercials, forests, ...; so it is beneficial having the ability to style it separately from a general background which would also be used outside towns/villages/...). Z8 would still provide good rendering potential, if Z7 would be oversized by residential.
  * For low zoom levels (e.g. < Z10), generalized polygons aggregating neighboring residential areas and eliminating out small holes/"bays"/"peninsulas" might be even better, but I gess that would be an own issue ...
  * in case of size problems: smaller areas could be filtered in ZL <=9 without much impact, I think, while having residential areas of larger cities even in ZL7 is quite important (problem might be if they are split into many individual pieces in OSM).
* commercial, retail, railway: similar to residential, although less important at smaller ZLs (usually areas are smaller and will appear in visible sizes later anyway). I guess, ZL>=10 would work fine.
* military: so far we are rendering them in ZL>=11, but for really large areas, availability in smaller levels would probably be good. I guess, these will pose less of a size problem, because they are not that abundant?

**Comment by manuelroth** [comment]
Thanks for your suggestions @numenor. Created a PR with the necessary changes (#312).
- As suggested the additional landuse data is present in the vector tiles as following:
z7-z14: residential
z10-z14: commercial, retail, railway, industrial
z11-z14: military
- The data can be style either by filter with the class or type attribute, both have the same value (one of residential, commercial, retail, railway, industrial, military)
- style example:
```
{
    "id": "landuse_residential",
    "type": "fill",
    "metadata": {
        "mapbox:group": "1444849388993.3071"
    },
    "source": "mapbox",
    "source-layer": "landuse",
    "interactive": true,
    "filter": [
        "==",
        "class",
        "residential"
    ],
    "paint": {
        "fill-color": "#d3d3d3"
    }
}
```
- The impact on size is minimal, as the data gets filtered by area like forest and wood. Check it with the tile-inspector.
- We also have to find a good place to document this, so other people know that there is additional data in our vector tiles which are not included in Mapbox Streets v7
