### ISSUE TITLE
Merge-jobs fails with mock-s3 (possibly documentation)

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#333]
This is a three part issue, possibly due to documentation:

1) By default using mock-s3, once all the processing is complete and "docker-compose run merge-jobs" is executed, I can see the attempt made to grab the jobs from mock-s3. Same is noticed with the merge-jobs.py script in standalone. However, the URL is incorrect, it is "http://mock-s3:8080"... which of course fails. The net result is a blank planet.mbtiles

If I hard-code "localhost:[port]", it works.

Is there an exportable variable such that the correct url for mock-s3 is picked up or should one be added?

2) When it says "Download http://....mbtiles (66.0 kB)" and then "Merge 10.2 kB from ....mbtiles", is that there's duplication in the resultant mbtiles and that the merge is only take of course the new info?

3) I've also hardcoded the RabbitMQ URL for the merge-jobs.py script as it isn't clear what format the rabbitmq_url is to be. I tried "amqp://osm:osm@localhost:5672/" which didn't seem to be correctly parsed. Once I hard coded it with Pika, it seemed to work fine. 

4) Is the expection made that a blank planet.mbtiles is made first to append the merge to? Should this be integrated into the merge-jobs.py script?

Sorry for all the questions, I'm working on an entire planet import so I will be running into the same issues that are quietly handled in the background for the planet.mbtiles download you provode

**Comment by lukasmartinelli** [comment]
Thank you for your patience.

> 1) By default using mock-s3, once all the processing is complete and "docker-compose run merge-jobs" is executed, I can see the attempt made to grab the jobs from mock-s3. Same is noticed with the merge-jobs.py script in standalone. However, the URL is incorrect, it is "http://mock-s3:8080"... which of course fails. The net result is a blank planet.mbtiles.

I guess you used the local Python script due to #331 not being available.
We don't use the mock-s3 in production but a hosted S3 provider.
If you run merge-jobs standalone this will not work but if you run it inside the merge-jobs container which is linked to the mock-s3 container the URL http://mock-s3:8080 will actually resolve to
the file (since Docker does host resolution).

> 2) When it says "Download http://....mbtiles (66.0 kB)" and then "Merge 10.2 kB from ....mbtiles", is that there's duplication in the resultant mbtiles and that the merge is only take of course the new info?

I download the MBTiles file and then check the size (66kb) then I merge it into the target file and show the difference before and after merge (10.2kB). This means that the merge source contained tiles that are already in the target file (and size therefore does not increase).


> 3) I've also hardcoded the RabbitMQ URL for the merge-jobs.py script as it isn't clear what format the rabbitmq_url is to be. I tried "amqp://osm:osm@localhost:5672/" which didn't seem to be correctly parsed. Once I hard coded it with Pika, it seemed to work fine.

It is always the same AMQP URI format in the form you mentioned `amqp://osm:osm@localhost:5672/`.
The wrapper script in the docker container that calls the Python script looks like this. It takes the env var from the docker container if it is set otherwise the default.

```sh
readonly RABBITMQ_URI=${RABBITMQ_URI:-"amqp://osm:osm@rabbitmq:5672/"}

function export_remote_mbtiles() {
    exec python merge-jobs.py "$RABBITMQ_URI" \
        --merge-target="$MERGE_TARGET"
}
```

This means you can set the RABBITMQ_URI in the docker-compose file as environment variable.

> 4) Is the expection made that a blank planet.mbtiles is made first to append the merge to? Should this be integrated into the merge-jobs.py script?

I was always using an older planet file I had before as merge target. But if you are starting from scratch that doesn't work as you said.
I could copy an empty MBTiles file into the repo for example that can be used as merge target. Would that work?

> Sorry for all the questions, I'm working on an entire planet import so I will be running into the same issues that are quietly handled in the background for the planet.mbtiles download you provode

Thanks for the patience for asking your way through. Never anticipated someone else would use the distributed workflow at big scale.
What about a Skype call (my user id "lukas.martinelli") so we can perhaps play through your problems directly. Since we've seen them a lot that can be quite effective and for us the process is always really helpful since we see exactly with what problems people struggle or we left undocumented.

I think a lot of this issue can be discoered if we put the entire process into the Travis build as well so it is always played through.

**Comment by stirringhalo** [comment]
> I guess you used the local Python script due to #331 not being available.
We don't use the mock-s3 in production but a hosted S3 provider.
If you run merge-jobs standalone this will not work but if you run it inside the merge-jobs container which is linked to the mock-s3 container the URL http://mock-s3:8080 will actually resolve to
the file (since Docker does host resolution).

Odd, when using the merge-jobs docker container, it didn't seem to properly do host resolution. merge-jobs.py knew the .mbtiles were on the mock-s3 store but when the attempt was made to download it, all the sizes were 0 kB. Granted my tiling area is larger than my test pbf import (small city) so some 0kB .mbtiles are expected. With it hard-coded, I had some .mbtiles as expected >0 kB. I will see if I can diagnose this a bit further. Don't sweat this as the workaround is easy.

> It is always the same AMQP URI format in the form you mentioned amqp://osm:osm@localhost:5672/. The wrapper script in the docker container that calls the Python script looks like this. It takes the env var from the docker container if it is set otherwise the default.

That may be it. I was running the merge-jobs.py script directly, so it wasn't picking up the AMQP_URI variable correctly. Will report back!

> I could copy an empty MBTiles file into the repo for example that can be used as merge target. Would that work?

Sounds like a good solution. What is the advantage for using a merge target? Does it take less time to merge as you only merge in the tiles which have changed?





Odd, I haven't had any success even with the mock-s3 container with host resolution. I haven't pulled it apart yet, but it appears the merge-jobs script knows the .mbtiles are there, but when the attempt is made to download, no .mbtiles are successfully retrieved and merged. With the hard-coded mock-s3, it works fine and generates a nice .mbtiles (working on a small city now to confirm the process)

**Comment by stirringhalo** [comment]
Oh, and thanks for the Skype call offer. At this point I really only have questions when I come across them, so not worth it. And it's probably best to have the conversation here so that there's a log of it for others! Most of my questions will probably resolve around tuning and optimizing, especially with regards to job sizing.

**Comment by stirringhalo** [comment]
Looks like I'm still facing the same issues. I'm not sure if the issue is arising from domain resolution, but each merge line of known good data looks like:

Download "http://mock-s3:8080/osm2vectortiles-jobs/{string}.mbtiles ({some amount greater than 66kB})
Merge 0 Bytes from {string}.mbtiles into /data/export/planet.mbtiles

The planet.mbtiles in ~/osm2vectortiles-2.0/export never seems to grow with the additional data.

If I do merge two mbtiles manually with say https://pypi.python.org/pypi/umimbutil, it works just fine.

I will make one last attempt at this with an already existing .mbtiles of some random area in export. It appears as the merging task is failing as the planet.mbtiles is empty.

**Comment by stirringhalo** [comment]
As a followup, here's my approach for now instead of the docker merge-jobs. Plus, this doesn't take the messages out of the queue:

`sudo apt-get install sqlite3`
`export MOCKS3_URI=http://localhost:[port]/osm2vectortiles-jobs`
`curl $MOCKS3_URI| grep Key | cut -d “>” -f 2 | cut -d “<” -f 1 | grep mbtiles > mbtiles`
`<mbtiles xargs -I % wget $MOCKS3_URI/% -O ~/mbtiles/%`
`wget https://raw.githubusercontent.com/mapbox/mbutil/master/patch`
`chmod +x patch`
`mkdir output`
`mv $(ls | sort -n | head -1) output/planet.mbtiles`
`for i in *.mbtiles; do ./patch $i output/planet.mbtiles; done`

**Comment by lukasmartinelli** [comment]
> As a followup, here's my approach for now instead of the docker merge-jobs. Plus, this doesn't take the messages out of the queue:

That's a good approach for doing initial renderings. Used this before for example to recover lost MBTiles.
Good idea.

**Comment by lukasmartinelli** [comment]
Mock S3 is no longer supported as of 1-2 months. But the discussion triggered here is still worth a lot. Thanks @stirringhalo.

I know this makes it a bit trickier to test - but we only had problems with the mock server
