### ISSUE TITLE
MIssing tables after diff import

### ISSUE THREAD

**Issue by rpieciorak** [osm2vectortiles/osm2vectortiles#373]
After running `import-osm-diff`, generating changed tiles list and running `export-list`, there are missing tables in POSTGIS.

```
Starting osm2vectortiles_pgdata_1
/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Postgis Plugin: ERROR:  relation "landuse_z13toz14" does not exist
LINE 1: SELECT ST_SRID("geometry") AS srid FROM landuse_z13toz14 WHE...
                                                ^
in executeQuery Full sql was: 'SELECT ST_SRID("geometry") AS srid FROM landuse_z13toz14 WHERE "geometry" IS NOT NULL LIMIT 1;'
```

I could regenerate all tables via `import-sql` but maybe this should be done automatically.

**Comment by lukasmartinelli** [comment]
I get it now. Since we need to recreate the derived tables (like subdivided polygons) we need to drop the views that need them and that is why you have to recreate them with `import-sql`.

However for me this does not pose a big problem and I would leave it like that - or the import step gets even more complicated as it is now.
