### ISSUE TITLE
Iran tile

### ISSUE THREAD

**Issue by ayratinirani** [osm2vectortiles/osm2vectortiles#381]
I wanna make an offline tile server for intranet and want tile of iran in 0 to 19 zooms

**Comment by klokan** [comment]
Download the tiles from
https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/extracts/iran.mbtiles
and follow how-tos in this project.
Vector tiles are 0-14 - but your can render these on 0-22 easily - with TileServer-GL or TileServer-Mapnik.

Iran country extract is (and always was) available in the Download section:
<img width="1042" alt="screen shot 2016-07-25 at 09 50 09" src="https://cloud.githubusercontent.com/assets/59284/17094089/496ad6c0-524d-11e6-8d88-b394269497ec.png">

**Comment by ayratinirani** [comment]
Is there any way to serve vector or png maps by php and js completely
offline?

در تاریخ ۲۵ ژوئیهٔ ۲۰۱۶ ۱۲:۲۲ ب.ظ، "Petr Pridal" <notifications@github.com>
نوشت:

**Comment by klokan** [comment]
Yes of course - the maps can run completely offline.

If you need PNG tiles then: tileserver-gl, or older tileserver-mapnik
If you need vector tiles in browser, then tileserver-gl-light, or tileserver-php with an external directory in Apache containing HTML+JavaScript+JSON from similar to https://github.com/klokantech/osm2vectortiles-gl-styles (made for tiles version 1 of osm2vectortiles now).

The maps can display the street names in Iran with an Arabic font too...

We have a USB stick desktop application as well - for Windows and Mac OS X - showing the maps offline directly without a need to have another application installed on a desktop - as a demo of the offline use. If you need commercial support contact us at https://www.klokantech.com/contact/, otherwise study the source code a available documentation in this project.

**Comment by lukasmartinelli** [comment]
> I wanna make an offline tile server for intranet and want tile of iran in 0 to 19 zooms

I really like the idea!!! Hope you can make some progress.
Thanks @klokan for answering.
