### ISSUE TITLE
Unacknowledged messages

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#382]
Question about handling unacknowledged messages, pardon any misunderstanding of RabbitMQ.

It seems that a fair number of messages are unacknowledged despite heartbeat being disabled. 

I am doing full planet renders at zoom level 6, so there are 4097 tiles which on average take an hour (but some take much longer).

Generally for a full planet, I have 8-12 unacknowledged messages, which has recently jumped to 60.

Here are my settings: 
- blocked_connection_timeout=1200
- render_timeout= 54000
- tile_timeout = 54000000

What's the best way to requeue those unack'd messaged? Kill all the connections in RabbitMQ and startup the cluster again? 

or...

`try:

```
        channel.basic_ack(delivery_tag=method_frame.delivery_tag)

        result_msg = handle_message(
            tm2source, bucket,
            functools.partial(s3_url, host, port, bucket_name),
            body
        )

        durable_publish(channel, result_queue_name,
                        body=json.dumps(result_msg))
    except:
        channel.basic_ack(delivery_tag=method_frame.delivery_tag)
        durable_publish(channel, failed_queue_name, body=body)
        channel.stop_consuming()
        time.sleep(5)  # Give RabbitMQ some time
        raise
```

`

Move the ack ahead of the tiling? That way, the message gets immediately acknowledged. If it dies later in tiling, it still fails the try and the message goes to the failed queue.

Thoughts?

**Comment by klokan** [comment]
My comment: Don't use (patched) RabbitMQ - use instead a true job queue, like Beanstalkd - for example via https://github.com/klokantech/cloudwrapper

I have recommended this to @lukasmartinelli as well, but it did not make it to the project before the bachelor thesis was finished. He started to work on it ...

See: https://github.com/osm2vectortiles/osm2vectortiles/issues/251#issuecomment-211758388

**Comment by stirringhalo** [comment]
Yep, I remember that. For now rabbitmq works mostly fine but I understand some of the advantage for beanstalk.

For now (and for others to see), my fix is when only unacknowledged messages are left, kill all the connections and restart all the workers.

But it's a pain without a script to kill all connections.

**Comment by stirringhalo** [comment]
Testing here: #383

**Comment by lukasmartinelli** [comment]
Thanks @stirringhalo @klokan 

> It seems that a fair number of messages are unacknowledged despite heartbeat being disabled.

Yes it is a real problem. And in the end causing missing tiles.

If you disable the heartbeat you have messages that are forever in the "pending" state if workers fail. Those are the "fair number of messages are unacknowledged despite heartbeat being disabled."

If you enable it you will have jobs that time out and will never finish.


> I have recommended this to @lukasmartinelli as well, but it did not make it to the project before the bachelor thesis was finished. He started to work on it ...

I actually had a branch with beanstalkd as message queue. Even tried it out but it didn't bring the immediate benefits i wanted (but probably fault on my side).

> What's the best way to requeue those unack'd messaged? Kill all the connections in RabbitMQ and startup the cluster again?

Tried that before.

> Don't use (patched) RabbitMQ - use instead a true job queue, like Beanstalkd - for example via https://github.com/klokantech/cloudwrapper

In the defense of RabbitMQ :) 
It is actually a fault at application level (even though I think RabbitMQ shouldn't be so strict). The application level should continuously call the `send_events` call to confirm that is still working. Problem is that we call the tilelive subprocess and then just block.
Better would be to have the subprocess and consumer in different threads (but then it get's complicated again..).


## How to proceed

2 alternatives.

## Fix RabbitMQ process

Pros:
- Components still work
- I really like working with the pipe tools to administer the jobs

Cons:
- In the end it will be a hacky solution
- A lot of time has already been spent solving this problem - perhaps dead end

## Different job queue -> beanstalkd

Pros:
- Solving the timeout thing once and for all

Cons:
- Rewrite `merge-jobs`, `generate-jobs` and `export-worker`

Option 2  is more feasible now than earlier because now I have no deadline of finishing up the thesis. And can invest time in stuff like this.
I know @klokan is for option 2 as well.

**Comment by stirringhalo** [comment]
> How to proceed
>
> 2 alternatives.
>
> Fix RabbitMQ process
>
> Pros:
>
> Components still work
> I really like working with the pipe tools to administer the jobs
> Cons:
> 
> In the end it will be a hacky solution
> A lot of time has already been spent solving this problem - perhaps dead end
> Different job queue -> beanstalkd
>
> Pros:
>
> Solving the timeout thing once and for all
> Cons:
>
> Rewrite merge-jobs, generate-jobs and export-worker
> Option 2 is more feasible now than earlier because now I have no deadline of finishing up the thesis. And can invest time in stuff like this.
> I know @klokan is for option 2 as well.

Without knowing much about beanstalkd, I'm personally in favour of RabbitMQ as its a known quantity with known issues. We also have less breaking commits.

**Comment by klokan** [comment]
RabbitMQ is designed for messaging - millions of small messages, short living inter-process communication, typically in web environments with HTTP health check / open connections, etc.
This is not what OSM2VectorTiles tile rendering on a hybrid cluster does...

We have used beanstalkd in tests on large production cluster deployments. It was fine and fitting the task - able to replace Amazon SQS or Google Task Queue API directly.

The cloudwrapper library is now released, which makes the switch easier. See: 
https://github.com/klokantech/cloudwrapper/blob/master/cloudwrapper/btq.py
This includes methods for auto reconnect, extending TimeToRun on long running tasks, etc.

Putting the jobs from command line almost like with https://github.com/lukasmartinelli/pipecat seems to be quite easy as well with https://github.com/nutrun/lentil/tree/master/lentil

Decission is on @lukasmartinelli...
