### ISSUE TITLE
Question: where cutting (subdivision) of geometry is performed? 

### ISSUE THREAD

**Issue by romanshuvalov** [osm2vectortiles/osm2vectortiles#403]
I'm inspecting the code to understand how it works. 

Everything is quite clear, but I can't find line where geometry is cut (subdivided) into parts to fit tiles. I was looking for something like `ST_Subdivide` or `ST_Split`, but only found initial subdivisions of oceans. That's not that I was looking for. 

`tm2source` only contains `WHERE geometry && !bbox!` clause to pick only objects related to tile but it does not split lines and polygons by edges of tile. 

I'm assuming  `tilelive-copy` do it internally, is that right?

**Comment by lukasmartinelli** [comment]
> I'm inspecting the code to understand how it works.
> 
> Everything is quite clear, but I can't find line where geometry is cut (subdivided) into parts to fit tiles. I was looking for something like ST_Subdivide or ST_Split, but only found initial subdivisions of oceans. That's not that I was looking for.
> 
> tm2source only contains WHERE geometry && !bbox! clause to pick only objects related to tile but it does not split lines and polygons by edges of tile.
> 
> I'm assuming tilelive-copy do it internally, is that right?

This is all Mapnik. We just give it the geometries within the BBOX it requests (`!bbox! `).
Why we subdivide the tiles is that we don't ship gigabytes of data to Mapnik it does not need (because we always send back all polygons that touch the bounding box).

You can also return everything (by not having a `WHERE bbox` clause) and then Mapnik will just throw everything away that is not in that tile (inefficient but good as example).

**Comment by romanshuvalov** [comment]
So, in this project, `tilelive` internally uses `mapnik` functionality to do this job, right?

**Comment by lukasmartinelli** [comment]
> So, in this project, tilelive internally uses mapnik functionality to do this job, right?

Exactly. Tilelive is just a wrapper around Mapnik (well with a lot of less important steps between).
