### ISSUE TITLE
Eventually integrating openstreetmap-mapboxgl

### ISSUE THREAD

**Issue by stirringhalo** [osm2vectortiles/osm2vectortiles#411]
I'd like to get your feedback on eventually integrating [openstreetmap-mapboxgl](https://github.com/stirringhalo/openstreetmap-mapboxgl) into osm2vectortiles and maintaining it as a separate tile schema and style from the rest of osm2vectortiles? It doesn't even have to be part of official vector tiles you host, just have it part of master.

My branch of osm2vectortiles (openstreetmap-style) adds `generate-tm2source` and `import-osm2pgsql` as docker containers. `import-osm2pgsql` imports the PBF using osm2pgsql and gets the official shapefiles for lower zooms. It follows the switch2osm build path.

`generate-tm2source` gets a copy of https://github.com/stirringhalo/openstreetmap-carto-vector-tiles and generates the appropriate .yml with the database access settings, etc. The tile schema overall follows the openstreetmap-carto one very closely (with minor changes from https://github.com/geofabrik/openstreetmap-carto-vector-tiles which actually kicked this off). The only significant changes I am adding are a combined roads layer to ease later rendering. I am waiting on a few rendering/styling issues before it goes fully 100%.

Styling-wise, I am doing a simplified openstreetmap-carto with no pattern fills on polygons and missing some minor layers. My next major focus is proper road stacking, which is non-trivial (and in fact not even Mapbox itself gets 100% correct at times esp. on tunnels).

Thoughts?

**Comment by pnorman** [comment]
> My next major focus is proper road stacking, which is non-trivial (and in fact not even Mapbox itself gets 100% correct at times esp. on tunnels).

Abandon all hope before looking at the roads code ;) The roads MSS is about 40% of osm-carto, and a significant portion of the SQL. It tries to get everything right, more so than any other style out there. There are a grand total of approximately zero people who fully understand it.

I would add that I think the osm-carto queries are badly suited for server-side vector tile rendering and worse for client-side vector tile rendering, but if you can get it working well I applaud your work.

**Comment by stirringhalo** [comment]
> Abandon all hope before looking at the roads code ;) The roads MSS is about 40% of osm-carto, and a significant portion of the SQL. It tries to get everything right, more so than any other style out there. There are a grand total of approximately zero people who fully understand it.

Ha! I've been diving into how osm-carto interacts with the SQL selections. I think I get it, sorta...ish. :confused: 

I have a plan for getting it to work, most of the hiccups are with Mapbox Style Spec. There's some new property functions that are in the works for lines. Just waiting for line-dasharray to be supported for property functions. The roads SQL will be majorly hacked up from the original, it's the only one that needs to be.

> I would add that I think the osm-carto queries are badly suited for server-side vector tile rendering and worse for client-side vector tile rendering, but if you can get it working well I applaud your work.

They aren't actually half bad. Speeds for one worker are about 50-60 tiles per second for Switzerland. IIRC that's in the range of my planet builds using OSM2VectorTiles.

**Comment by mboeringa** [comment]
> It tries to get everything right, **more so than any other style out there**

I politely disagree ;-)

There is at least one other style and renderer that gets about everything right, and that is the one I developed from the ground up for ArcGIS, and yes, there is a grand total of one person that understands it...

But there ends the joke, because I do share and understand your pain: _it is hard!_ 

For my ArcGIS renderer, I partly took the sting out of it, by making optimal use of ArcGIS's options like Symbol Level drawing to first stack the road types in a meaningful order, and then use the ability to re-order ArcGIS Table Of Contents thematic layers to fully automatically and dynamically stack them according to the OSM "layer" key.

This required some really hard thinking though, of what that program code should look like (which I developed in Python using ArcGIS's "arcpy" package), and a considerable amount of frustration to get it right and fix the bugs (and the logic). The final code stacks ArcGIS thematic layers, each representing a single OSM "layer" value, where each thematic layer defines all road types, and can even do this for multiple different thematic layers developed for different zoom levels (and even man_made=bridges).

The final ordering code that moves the thematic layers around in ArcGIS's TOC is quite elegant and not extremely long.

Below is a nice - **but special case!** - example. It is special, because the same code that drives the stacking and ordering for normal linear ways, has been used here to additionally stack OSM's **area:highway=x** features, which are _Polygon_ representations of road surfaces. You can even see it correctly stacking normal "linear" roads, and two tram ways (the thin black lines running below the viaduct) in a mix of these feature types.

The corresponding carto rendering (only based on linear way objects) - also looking good and technically correct by the way! - can you view via this link:
https://www.openstreetmap.org/search?query=szczecin#map=17/53.42584/14.56509

![arcgis_renderer_for_openstreetmap-area_highway2](https://cloud.githubusercontent.com/assets/7635726/17984865/7691a2b2-6b13-11e6-9963-fc18ee99b4cd.png)

**Comment by stirringhalo** [comment]
@mboeringa 
Wow, very nice looking. I agree 100% it's a pain in the ... . I actually just got it working properly with Mapbox GL JS and Openstreetmap tile schema.

Still lots of work to be done to make it zoom dependent widths and including railroads+paths (which at this point don't work the best with the approach I have) but stacking works 100%, even when it gets really hairy in the stacking!! 

Keep an eye on http://45.56.99.211/ in the next day or two for the latest developments.

**Comment by stirringhalo** [comment]
> I would actually prefer to see it in a seperate repository inside OSM2VectorTiles instead of of two ways go generate vector tiles in the master branch.

Okie dokes!

> I think it fits perfectly into the organization because it "turns OSM into vector tiles" but is a different approach (but one I really appreciate and am very happy to see realized!!).
I would like to keep it under the OSM2VectorTiles umbrella but as you wish. You can also take it to your own repo if you want.

I'm very happy to move it into the OSM2VectorTiles organization. I will do so once I have the road styling more complete. I have just figured out how to do proper road stacking, still need to figure out tracks but that should be mostly straight-forward!

> We can even promote it on the website etc. since I like it but it kind of a different project we started here although using the same approach.
> 
> Whether we will prerender them and how to serve them will be a different topic :grin: 
But perhaps we find someone to sponsor a rendering.

I can do the rendering :smile: I have a machine to do it on. I can upload a rendering, probably on a monthly interval.

At this stage I am using the line2 branch of mapbox-gl-js as I need the data property functions for lines so I can properly do roads.
