### ISSUE TITLE
How to display local language labels

### ISSUE THREAD

**Issue by bearnxx** [osm2vectortiles/osm2vectortiles#420]
I have host my own tile server but I found the labels are all English. How could I display Chinese  in my map?

**Comment by klokan** [comment]
Replace in your JSON style the "name_en" by "name_zh".

**Comment by klokan** [comment]
You may also need to install on your server an unicode font and add it to your JSON style.
This is a free unicode font we have released:
https://github.com/klokantech/klokantech-gl-fonts
and for use it you must have in the style:
```
 "text-font": [
                    "KlokanTech Noto Sans Regular",
                    "KlokanTech Noto Sans CJK Regular"
                ],
```
Here is a live preview of the font https://maps.klokantech.com/ - deep zoom to China to see street names and other labels.

**Comment by bearnxx** [comment]
Ok  I'll try it later  
Thank you very much. 
@klokan

**Comment by klokan** [comment]
Let us know if you succeed or of there are troubles. I am closing this ticket now - we can reopen. Good luck!

**Comment by bearnxx** [comment]
it worked !  thank you very much.

but there are still some little problems some labels in Europ or USA are still English and some are chinese.
how to fix this? thank you for your patience.

**Comment by ImreSamu** [comment]
@bearnxx :  ( part 2 )
More info about  OpenStreetMap names: 
 * http://wiki.openstreetmap.org/wiki/Names
 * http://wiki.openstreetmap.org/wiki/Multilingual_names

The Mapbox definition for `name_zh`:
 * _"name_zh : Chinese* (if available, otherwise same as name)"_  
   * https://www.mapbox.com/vector-tiles/mapbox-streets-v7/

Wordwide OSM Taginfo stat for  `name:zh` :
 *  http://taginfo.openstreetmap.org/search?q=name%3Azh
 * map : http://taginfo.openstreetmap.org/keys/name%3Azh#map
