### ISSUE TITLE
are the tiles in *.mbtiles files pbf format?

### ISSUE THREAD

**Issue by bearnxx** [osm2vectortiles/osm2vectortiles#433]
I opened a mbtiles file with a SQLite Browser and I found a talbe like below.
I wonder does the BLOB field tile_data store pbf format file? and if so , how can I deserialize it with python or js.   thank you 
![123](https://cloud.githubusercontent.com/assets/21222866/18715382/9feb6268-804b-11e6-887b-4622de9d38b8.png)

**Comment by lukasmartinelli** [comment]
> I opened a mbtiles file with a SQLite Browser and I found a talbe like below.
> I wonder does the BLOB field tile_data store pbf format file? and if so , how can I deserialize it with python or js. thank you

The BLOB is a **gzipped PBF** file!
To work with it you first need to unzip it and then parse with a MVT parsing library.

Check https://github.com/osm2vectortiles/osm2vectortiles/blob/master/tools/compare/tileInfo.jsfor an example.

**Comment by bearnxx** [comment]
I have got some information like picture below, but I still want to know the detail information in the [object] list. and How can I resolve them. thank you :)
![111](https://cloud.githubusercontent.com/assets/21222866/18748785/730c7802-8106-11e6-9494-1fe511ab9489.PNG)

**Comment by manuelroth** [comment]
> I have got some information like picture below, but I still want to know the detail information in the [object] list. and How can I resolve them. thank you :)

As lukas suggested to read the detail information you need to parse this with a MVT parsing library:

[MVT Library for Python](https://github.com/mapbox/vector-tile-py)
[MVT Library for JavaScript](https://github.com/mapbox/vector-tile-js)

Example of MVT JavaScript library which outputs all layers in a vector tile:
```javascript
zlib.unzip(tile, function(err, tile) {
	    if (!err) {
      		var rawTile = new VectorTile(new Protobuf(tile))
      		var tileLayers = rawTile.layers;
      		console.log(tileLayers);
      	}
});
```
In the example above you can see that the tile gets unzipped, read with the Protobuf library, and then with the [MVT Javascript Library](https://github.com/mapbox/vector-tile-js). Mapbox Vector Tiles are stored in a highly optimized way. So the representation in your picture above is not suitable to work with. It is necessary to use the MVT Library in order to correctly read an Mapbox Vector Tile.
