### ISSUE TITLE
Water Polygons in openlayers are half filled in

### ISSUE THREAD

**Issue by jdeboer-geoplan** [osm2vectortiles/osm2vectortiles#507]
Using openlayers 3 to display the pbf files has water tiles half filled in.  Is this a problem with the pbf files or with openlayers?  Its not a problem in mapbox gl

e.g.
![avsq2](https://cloud.githubusercontent.com/assets/23341752/21992326/e5bc24b2-dc0d-11e6-91b0-ca29b226d1d1.png)

**Comment by stirringhalo** [comment]
That's very curious, are you only seeing that with your own mbtiles or is that visible on osm2vectortiles.org?

This repo is superceded by https://github.com/openmaptiles/openmaptiles due to https://github.com/osm2vectortiles/osm2vectortiles/issues/387 but I'm curious about this as it may popup elsewhere.

**Comment by ischas** [comment]
Maybe related to https://github.com/openlayers/openlayers/pull/6358

**Comment by jdeboer-geoplan** [comment]
If I use http://osm2vectortiles-2.tileserver.com/v1/{z}/{x}/{y}.pbf I still see the issue, That openlayers bug looks like it could be the problem I'll get the fix, try again and report back.

**Comment by jdeboer-geoplan** [comment]
Ok, yes it was https://github.com/openlayers/openlayers/pull/6358 I fixed it by giving the water a stroke.

Thank you for the quick reply.
