### ISSUE TITLE
Ignore Water Tiles: prevent rendering

### ISSUE THREAD

**Issue by klokan** [osm2vectortiles/osm2vectortiles#74]
In #42 we have discussed several approaches for handling water tiles. The selected dummy approach was the render the water - and in post-processing remove it from the produced MBTiles.

Here we should track improved process preventing rendering of empty tiles - as discussed in #42:

> ## Variant 1: Query Data in Worker
> 
> One is to do the decision whether to render all tiles of z8 directly in the worker and avoid doing any extra work. In this case we need to query whether the source *would* render data. We need to build a query that is coupled to the source project.
> 
> Pros:
> - 24% savings in rendering time
> - No additional component needed
>
> Cons:
> - Prone to errors (query needs to be pretty close to the actual source project query)
> - More complex approach
> - How do we know that we haven't missed something?

**Comment by klokan** [comment]
The `tl` command is to dummy - it can in fact be more clever and stops: https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/export/export-local.sh#L16

**Comment by lukasmartinelli** [comment]
Some thoughts...

After we have the updating process in place we need to render the world once (which is expensive once). After that we only update the changed parts (which we hope will be cheap when done continuously).

Ignoring the water directly only saves 24% of the first rendering. For the update the ignore water feature doesn't help to improve performance at all - since empty areas won't have any OSM edits.

Yet another way to approach it is since we already rendered the world once we now know where the water is (from the subpyramid removal tool) and can prevent rendering directly based on a dataset that tells us which pyramids are water. This of course will not incorporate changes to empty areas that are now no longer empty (like if someone added a label to a large sea) - but I guess this is a really rare event.

**Comment by lukasmartinelli** [comment]
My solution now is the same as in **v1.0**  (but automated) see the statement above for the justification.

Before the `export_remote` worker uploads the MBTiles file to S3 it will optimize it and **remove all subpyramids that contain the same data** (using the Python module from https://github.com/lukasmartinelli/mbtoolbox directly).
