### ISSUE TITLE
SQL Files missing from update-scaleranks docker

### ISSUE THREAD

**Issue by leblowl** [osm2vectortiles/osm2vectortiles#82]
Hey all! I am trying to demo this awesome repo & upon following the setup steps in the .travis.yml file, `docker-compose run update-scaleranks` fails with missing sql files: https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/update-scaleranks/update-scaleranks.sh#L22-L24. Then upon trying to export anyway I get a failure due to missing osm_countries table. Related: osm2vectortiles/osm2vectortiles#80

As a side note, getting python to display the text from the tl subprocess when it fails in the export docker could be a really handy enhancement. So that way I don't have to `docker run` the export and exec the command by hand to see why it fails. Currently it only displays the exit code. Sweet, ty

**Comment by lukasmartinelli** [comment]
Sorry for the inconvenience. That's why we should keep the master branch stable at all time :/
It also should have been documented better, but Travis was the right place to take a look :+1: 

In the https://github.com/osm2vectortiles/osm2vectortiles/tree/feature/optimize-water-tiles branch are the newest changes, we will merge this soon so the issues you mentioned should be fixed.

> Hey all! I am trying to demo this awesome repo & upon following the setup steps in the .travis.yml file, docker-compose run update-scaleranks fails with missing sql files: https://github.com/osm2vectortiles/osm2vectortiles/blob/master/src/update-scaleranks/update-scaleranks.sh#L22-L24. Then upon trying to export anyway I get a failure due to missing osm_countries table. Related: osm2vectortiles/osm2vectortiles#80

We have changed the way we import our custom labels. Should be good in the next merge.

> As a side note, getting python to display the text from the tl subprocess when it fails in the export docker could be a really handy enhancement. So that way I don't have to docker run the export and exec the command by hand to see why it fails. Currently it only displays the exit code. Sweet, ty

We stop using a Python wrapper around `tl` in the next release so you get the raw output.
The wrapper is only used when using multiple workers for processing - if someone just wants to do a local export he should get the raw `tl` output. Thanks for the input.

**Comment by manuelroth** [comment]
@leblowl The branch with the necessary changes is now merged. As proposed in #80 we have now a standalone export, it is called export-local. I would love to hear, if it works for you now.

**Comment by leblowl** [comment]
Sweet, thank you to all, everything works really well now, successfully finished export-local following the instructions in the README.md. Cheers! :beers:
